#!/usr/bin/env python3
"""Download and exercise only the public Gradient Data 0.2.0-rc.2 customer ZIP.

This consumer gate uses generated bytes and the installed CLI/SDK. It does not
build the engine or import a private source tree. The same-release .sha256 is an
integrity check; the release channel, not the checksum itself, identifies origin.
"""

import argparse
import hashlib
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys
import tempfile
from urllib.parse import quote
from urllib.request import Request, urlopen
import zipfile

VERSION = "0.2.0-rc.2"
ASSET = "Gradient_Data_0.2.0-rc.2_Linux_Windows_x86_64.zip"
ZIP_LIMIT = 128 * 1024 * 1024
EXPANDED_LIMIT = 256 * 1024 * 1024

ARTIFACTS = {
    "linux-x86_64/dgrad", "linux-x86_64/libgradient_data_c.so",
    "linux-x86_64/libgradient_data_c.a", "windows-x86_64/dgrad.exe",
    "windows-x86_64/gradient_data_c.dll",
    "windows-x86_64/gradient_data_c.dll.lib",
    "windows-x86_64/gradient_data_c.lib", "include/gradient_data.h",
    "include/gradient_data.hpp",
}
CUSTOMER_FILES = {
    "README.md", "SECURITY.md", "COMPATIBILITY.md", "SDK.md",
    "NOTICE.txt", "THIRD_PARTY_NOTICES.md",
    "licenses/rust/Apache-2.0.txt", "licenses/rust/MIT.txt",
    "licenses/rust/LLVM-exception.txt", "licenses/rust/COPYRIGHT-library.html",
    "cmake/GradientDataConfig.cmake", "examples/CMakeLists.txt",
    "examples/read_range.c", "examples/read_range.cpp",
    "install.sh", "uninstall.sh", "install.ps1", "uninstall.ps1",
    "install_linux.py",
}
THIRD_PARTY = {
    "block-buffer-0.10.4": ("LICENSE-APACHE", "LICENSE-MIT"),
    "cfg-if-1.0.4": ("LICENSE-APACHE", "LICENSE-MIT"),
    "cpufeatures-0.2.17": ("LICENSE-APACHE", "LICENSE-MIT"),
    "crypto-common-0.1.7": ("LICENSE-APACHE", "LICENSE-MIT"),
    "digest-0.10.7": ("LICENSE-APACHE", "LICENSE-MIT"),
    "generic-array-0.14.7": ("LICENSE",),
    "itoa-1.0.18": ("LICENSE-APACHE", "LICENSE-MIT"),
    "libc-0.2.186": ("LICENSE-APACHE", "LICENSE-MIT"),
    "memchr-2.8.2": ("COPYING", "LICENSE-MIT", "UNLICENSE"),
    "proc-macro2-1.0.106": ("LICENSE-APACHE", "LICENSE-MIT"),
    "quote-1.0.46": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_core-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_derive-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_json-1.0.150": ("LICENSE-APACHE", "LICENSE-MIT"),
    "sha2-0.10.9": ("LICENSE-APACHE", "LICENSE-MIT"),
    "syn-2.0.118": ("LICENSE-APACHE", "LICENSE-MIT"),
    "typenum-1.20.1": ("LICENSE", "LICENSE-APACHE", "LICENSE-MIT"),
    "unicode-ident-1.0.24": ("LICENSE-APACHE", "LICENSE-MIT", "LICENSE-UNICODE"),
    "version_check-0.9.5": ("LICENSE-APACHE", "LICENSE-MIT"),
    "zmij-1.0.21": ("LICENSE-MIT",),
}
PAYLOAD = ARTIFACTS | CUSTOMER_FILES | {
    f"licenses/{crate}/{license_name}"
    for crate, names in THIRD_PARTY.items() for license_name in names
}
PACKAGE_FILES = PAYLOAD | {"SHA256SUMS"}
assert len(PAYLOAD) == 71 and len(PACKAGE_FILES) == 72


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def download(tag, name, destination, limit):
    url = ("https://github.com/Gradient19/gradient-data/releases/download/"
           + quote(tag, safe="") + "/" + quote(name, safe=""))
    request = Request(url, headers={"User-Agent": "gradient-data-customer-smoke/1"})
    total = 0
    with urlopen(request, timeout=60) as response, destination.open("xb") as output:
        require(response.status == 200, f"download failed: HTTP {response.status}")
        while True:
            block = response.read(1024 * 1024)
            if not block:
                break
            total += len(block)
            require(total <= limit, f"download exceeds {limit} bytes: {name}")
            output.write(block)
    require(total > 0, f"empty download: {name}")


def check_sidecar(sidecar, archive):
    text = sidecar.read_text("ascii")
    match = re.fullmatch(r"([0-9a-f]{64})(?:  " + re.escape(ASSET) + r")?\r?\n?", text)
    require(match is not None, "invalid release ZIP checksum sidecar")
    require(sha256(archive) == match.group(1), "whole release ZIP checksum mismatch")


def check_zip(zip_path):
    require(zip_path.stat().st_size <= ZIP_LIMIT, "release ZIP exceeds size limit")
    with zipfile.ZipFile(zip_path) as archive:
        entries = archive.infolist()
        names = [entry.filename for entry in entries]
        require(len(entries) == len(PACKAGE_FILES), "release ZIP member count mismatch")
        require(set(names) == PACKAGE_FILES and len(set(names)) == len(names),
                "release ZIP exact file roster mismatch")
        require(len({name.casefold() for name in names}) == len(names),
                "release ZIP has case-colliding paths")
        total = 0
        for entry in entries:
            name = entry.filename
            require(name == Path(name).as_posix() and not name.startswith("/")
                    and "\\" not in name and ":" not in name
                    and all(part not in ("", ".", "..") for part in name.split("/")),
                    f"unsafe ZIP path: {name!r}")
            kind = stat.S_IFMT(entry.external_attr >> 16)
            require(kind in (0, stat.S_IFREG) and not entry.is_dir(),
                    f"nonregular ZIP member: {name}")
            require(not entry.flag_bits & 1, f"encrypted ZIP member: {name}")
            require(entry.compress_type in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED),
                    f"unsupported ZIP compression: {name}")
            require(entry.file_size <= EXPANDED_LIMIT, f"oversized ZIP member: {name}")
            total += entry.file_size
            require(total <= EXPANDED_LIMIT, "ZIP expansion limit exceeded")
    print("Whole ZIP digest, exact 72-file roster and expansion bounds PASS")


def extract_verified_zip(zip_path, root):
    # root is an empty directory created exclusively by TemporaryDirectory.
    require(not any(root.iterdir()), "extraction directory is not empty")
    with zipfile.ZipFile(zip_path) as archive:
        for entry in archive.infolist():
            target = root / entry.filename
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(entry) as source, target.open("xb") as output:
                shutil.copyfileobj(source, output, 1024 * 1024)
            require(target.stat().st_size == entry.file_size,
                    f"short ZIP member: {entry.filename}")
    if sys.platform == "linux":
        (root / "linux-x86_64/dgrad").chmod(0o755)
    verify_bundle(root)


def expected_dirs(files):
    return {"/".join(name.split("/")[:i]) for name in files
            for i in range(1, len(name.split("/")))}


def verify_bundle(root, installed=False):
    require(root.is_dir() and not root.is_symlink(), "bundle is not an ordinary directory")
    files, dirs = set(), set()
    for base, subdirs, filenames in os.walk(root, followlinks=False):
        for name in subdirs + filenames:
            item = Path(base) / name
            relative = item.relative_to(root).as_posix()
            mode = item.lstat().st_mode
            if stat.S_ISDIR(mode):
                dirs.add(relative)
            elif stat.S_ISREG(mode):
                files.add(relative)
            else:
                raise ValueError(f"nonregular package entry: {relative}")
    expected_files = PACKAGE_FILES | ({"INSTALL_RECEIPT"} if installed else set())
    require(files == expected_files and dirs == expected_dirs(PACKAGE_FILES),
            "package file or directory roster mismatch")
    manifest = (root / "SHA256SUMS").read_bytes()
    expected_manifest = "".join(
        f"{sha256(root / name)}  {name}\n" for name in sorted(PAYLOAD)
    ).encode("ascii")
    require(manifest == expected_manifest, "package SHA256SUMS or payload checksum mismatch")
    if installed:
        receipt = (f"Gradient Data {VERSION}\n" + hashlib.sha256(manifest).hexdigest()
                   + "\n").encode("ascii")
        require((root / "INSTALL_RECEIPT").read_bytes() == receipt,
                "installed bundle receipt mismatch")
    print("Installed" if installed else "Extracted", "public manifest and exact roster PASS")


def run(*command, env=None):
    result = subprocess.run([str(item) for item in command], env=env,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=180)
    if result.returncode:
        raise RuntimeError(f"command failed ({result.returncode}): {command!r}\n"
                           f"stdout: {result.stdout[-3000:]}\nstderr: {result.stderr[-3000:]}")
    return result


def clean_runtime_environment(bundle, environment):
    env = environment.copy()
    env.pop("LD_LIBRARY_PATH", None)
    if sys.platform == "win32":
        def in_bundle(text):
            try:
                path = Path(text).resolve()
                return path == bundle or bundle in path.parents
            except (OSError, ValueError):
                return False
        env["PATH"] = os.pathsep.join(part for part in env.get("PATH", "").split(os.pathsep)
                                      if part and not in_bundle(part))
    return env


def generated_input():
    # Deterministic non-power-of-two skew, with no private corpus or fixture.
    state = 0x48723995afcb02d1
    thresholds = (52, 92, 123, 150, 173, 192, 207, 219, 229, 237,
                  243, 247, 250, 252, 254, 255)
    raw = bytearray()
    for _ in range(300_003):
        state ^= (state << 13) & ((1 << 64) - 1)
        state ^= state >> 7
        state ^= (state << 17) & ((1 << 64) - 1)
        value = (state >> 24) & 255
        raw.append(next(i for i, limit in enumerate(thresholds) if value <= limit))
    return bytes(raw)


def exercise_installed(bundle, work, environment):
    windows = sys.platform == "win32"
    platform_dir = bundle / ("windows-x86_64" if windows else "linux-x86_64")
    cli = platform_dir / ("dgrad.exe" if windows else "dgrad")
    runtime = clean_runtime_environment(bundle, environment)
    data = generated_input()
    source = work / "synthetic.bin"
    source.write_bytes(data)
    require(run(cli, "--version", env=runtime).stdout.strip() == f"gradient-data {VERSION}",
            "installed CLI version differs from release")
    for mode in ("off", "local", "shared"):
        archive = work / f"{mode}.uacd"
        restored = work / f"{mode}.restored"
        segment = work / f"{mode}.range"
        run(cli, "pack", source, archive, "--profile", "fast", "--entropy", mode, env=runtime)
        magic = archive.read_bytes()[:8]
        require(magic == (b"DGRAD001" if mode == "off" else b"UACD0003"),
                f"unexpected {mode} archive version: {magic!r}")
        run(cli, "info", archive, env=runtime)
        run(cli, "verify", archive, env=runtime)
        run(cli, "range", archive, "260000", "8192", segment, env=runtime)
        require(segment.read_bytes() == data[260000:268192], f"{mode} range mismatch")
        run(cli, "unpack", archive, restored, env=runtime)
        require(restored.read_bytes() == data, f"{mode} unpack mismatch")
        blocked = subprocess.run([str(cli), "unpack", str(archive), str(restored)],
                                 env=runtime, capture_output=True)
        require(blocked.returncode != 0 and restored.read_bytes() == data,
                f"{mode} overwrite protection failed")
        print(f"{mode} CLI verify/range/unpack/no-overwrite PASS")

    build = work / "build"
    run("cmake", "-S", bundle / "examples", "-B", build,
        "-DGradientData_DIR=" + str(bundle / "cmake"), env=environment)
    run("cmake", "--build", build, "--config", "Release", env=environment)
    exe_dir = build / "Release" if windows and (build / "Release").is_dir() else build
    suffix = ".exe" if windows else ""
    if windows:
        dll = platform_dir / "gradient_data_c.dll"
        deployed = exe_dir / dll.name
        shutil.copyfile(dll, deployed)
        require(sha256(deployed) == sha256(dll), "deployed C SDK DLL differs from bundle")
    for name in ("read_range_c", "read_range_cpp"):
        executable = exe_dir / (name + suffix)
        for mode in ("off", "local", "shared"):
            run(executable, work / f"{mode}.uacd", env=runtime)
    print("C11 shared and C++17 static CMake consumers on all archives PASS")


def install_and_exercise(bundle, scratch):
    environment = os.environ.copy()
    if sys.platform == "win32":
        environment["LOCALAPPDATA"] = str(scratch / "local-app-data")
        prefix = scratch / "local-app-data/Programs/GradientData" / VERSION
        install = ["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy",
                   "Bypass", "-File", str(bundle / "install.ps1")]
        uninstall = ["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy",
                     "Bypass", "-File", str(bundle / "uninstall.ps1")]
    elif sys.platform == "linux":
        environment["XDG_DATA_HOME"] = str(scratch / "xdg-data")
        environment["XDG_BIN_HOME"] = str(scratch / "xdg-bin")
        prefix = scratch / "xdg-data/gradient-data" / VERSION
        install = ["sh", str(bundle / "install.sh")]
        uninstall = ["sh", str(bundle / "uninstall.sh")]
    else:
        raise RuntimeError("only Linux and Windows x86-64 runners are supported")
    require(not prefix.exists() and not prefix.is_symlink(), "test installation exists")
    run(*install, env=environment)
    require(prefix.is_dir() and not prefix.is_symlink(), "installer did not create prefix")
    verify_bundle(prefix, installed=True)
    usage = scratch / "usage"
    usage.mkdir()
    exercise_installed(prefix, usage, environment)
    run(*uninstall, env=environment)
    require(not prefix.exists() and not prefix.is_symlink(), "uninstaller left prefix")
    if sys.platform == "linux":
        link = scratch / "xdg-bin/dgrad"
        require(not link.exists() and not link.is_symlink(), "uninstaller left CLI link")
    print("isolated user-local install and uninstall PASS")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-tag", required=True,
                        help="tag of the published Gradient19/gradient-data release")
    arguments = parser.parse_args()
    tag = arguments.release_tag
    require(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", tag) is not None,
            "invalid public release tag")
    with tempfile.TemporaryDirectory(prefix="gradient-data-public-smoke-") as temporary:
        scratch = Path(temporary)
        zip_path = scratch / ASSET
        sidecar = scratch / (ASSET + ".sha256")
        download(tag, sidecar.name, sidecar, 256)
        download(tag, ASSET, zip_path, ZIP_LIMIT)
        check_sidecar(sidecar, zip_path)
        check_zip(zip_path)
        bundle = scratch / "bundle"
        bundle.mkdir()
        extract_verified_zip(zip_path, bundle)
        install_and_exercise(bundle, scratch)
    print("Public release customer smoke PASS")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, RuntimeError, zipfile.BadZipFile, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"customer smoke failed: {error}") from error
