#!/usr/bin/env python3
"""Download and exercise only the public Gradient Data 0.3.0-rc.3 customer ZIP.

This consumer gate uses generated bytes and the installed CLI/SDK. It does not
build the engine or import a private source tree. The same-release .sha256 is an
integrity check; the release channel, not the checksum itself, identifies origin.
"""

import argparse
import hashlib
import http.client
import json
import os
from pathlib import Path
import re
import queue
import shutil
import stat
import subprocess
import sys
import tempfile
import threading
from urllib.parse import quote, urlsplit
from urllib.request import Request, urlopen
import zipfile

VERSION = "0.3.0-rc.3"
ASSET = "Gradient_Data_0.3.0-rc.3_Linux_Windows_x86_64.zip"
ZIP_SHA256 = "c63b81d461b58d85b38d7448489309b83a1b7c21956319ecf2bad2dd275d0600"
ZIP_LIMIT = 8001897
EXPANDED_LIMIT = 256 * 1024 * 1024

ARTIFACTS = {
    "linux-x86_64/uacd", "linux-x86_64/uacd-gui", "linux-x86_64/libgradient_data_c.so",
    "linux-x86_64/libgradient_data_c.a", "windows-x86_64/uacd.exe", "windows-x86_64/uacd-gui.exe",
    "windows-x86_64/gradient_data_c.dll",
    "windows-x86_64/gradient_data_c.dll.lib",
    "windows-x86_64/gradient_data_c.lib", "include/gradient_data.h",
    "include/gradient_data.hpp", "include/uacd_archive.h", "include/uacd_archive.hpp",
}
CUSTOMER_FILES = {
    "README.md", "SECURITY.md", "COMPATIBILITY.md", "SDK.md",
    "NOTICE.txt", "THIRD_PARTY_NOTICES.md",
    "licenses/rust/Apache-2.0.txt", "licenses/rust/MIT.txt",
    "licenses/rust/LLVM-exception.txt", "licenses/rust/COPYRIGHT-library.html",
    "cmake/GradientDataConfig.cmake", "examples/CMakeLists.txt",
    "examples/read_range.c", "examples/read_range.cpp",
    "examples/read_member.c", "examples/read_member.cpp", "examples/runtime_asset_reader.c",
    "GUI.md", "start-gui.sh", "Start_Gradient_Data.cmd",
    "install.sh", "uninstall.sh", "install.ps1", "uninstall.ps1",
    "install_linux.py",
}
THIRD_PARTY = {
    "block-buffer-0.10.4": ("LICENSE-APACHE", "LICENSE-MIT"),
    "cfg-if-1.0.4": ("LICENSE-APACHE", "LICENSE-MIT"),
    "cpufeatures-0.2.17": ("LICENSE-APACHE", "LICENSE-MIT"),
    "crypto-common-0.1.7": ("LICENSE-APACHE", "LICENSE-MIT"),
    "digest-0.10.7": ("LICENSE-APACHE", "LICENSE-MIT"),
    "generic-array-0.14.7": ("LICENSE",),
    "itoa-1.0.18": ("LICENSE-APACHE", "LICENSE-MIT"),
    "libc-0.2.186": ("LICENSE-APACHE", "LICENSE-MIT"),
    "memchr-2.8.2": ("COPYING", "LICENSE-MIT", "UNLICENSE"),
    "proc-macro2-1.0.106": ("LICENSE-APACHE", "LICENSE-MIT"),
    "quote-1.0.46": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_core-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_derive-1.0.228": ("LICENSE-APACHE", "LICENSE-MIT"),
    "serde_json-1.0.150": ("LICENSE-APACHE", "LICENSE-MIT"),
    "sha2-0.10.9": ("LICENSE-APACHE", "LICENSE-MIT"),
    "syn-2.0.118": ("LICENSE-APACHE", "LICENSE-MIT"),
    "typenum-1.20.1": ("LICENSE", "LICENSE-APACHE", "LICENSE-MIT"),
    "unicode-ident-1.0.24": ("LICENSE-APACHE", "LICENSE-MIT", "LICENSE-UNICODE"),
    "version_check-0.9.5": ("LICENSE-APACHE", "LICENSE-MIT"),
    "zmij-1.0.21": ("LICENSE-MIT",),
}
PAYLOAD = ARTIFACTS | CUSTOMER_FILES | {
    f"licenses/{crate}/{license_name}"
    for crate, names in THIRD_PARTY.items() for license_name in names
}
PACKAGE_FILES = PAYLOAD | {"SHA256SUMS"}
assert len(PAYLOAD) == 81 and len(PACKAGE_FILES) == 82


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def download(tag, name, destination, limit):
    url = ("https://github.com/Gradient19/gradient-data/releases/download/"
           + quote(tag, safe="") + "/" + quote(name, safe=""))
    request = Request(url, headers={"User-Agent": "gradient-data-customer-smoke/1"})
    total = 0
    with urlopen(request, timeout=60) as response, destination.open("xb") as output:
        require(response.status == 200, f"download failed: HTTP {response.status}")
        while True:
            block = response.read(1024 * 1024)
            if not block:
                break
            total += len(block)
            require(total <= limit, f"download exceeds {limit} bytes: {name}")
            output.write(block)
    require(total > 0, f"empty download: {name}")


def check_sidecar(sidecar, archive):
    text = sidecar.read_text("ascii")
    match = re.fullmatch(r"([0-9a-f]{64})(?:  " + re.escape(ASSET) + r")?\r?\n?", text)
    require(match is not None, "invalid release ZIP checksum sidecar")
    require(match.group(1) == ZIP_SHA256, "release ZIP checksum differs from pinned digest")
    require(archive.stat().st_size == ZIP_LIMIT, "release ZIP size differs from pinned size")
    require(sha256(archive) == ZIP_SHA256, "whole release ZIP checksum mismatch")


def check_zip(zip_path):
    require(zip_path.stat().st_size == ZIP_LIMIT, "release ZIP size differs from pinned size")
    with zipfile.ZipFile(zip_path) as archive:
        entries = archive.infolist()
        names = [entry.filename for entry in entries]
        require(len(entries) == len(PACKAGE_FILES), "release ZIP member count mismatch")
        require(set(names) == PACKAGE_FILES and len(set(names)) == len(names),
                "release ZIP exact file roster mismatch")
        require(len({name.casefold() for name in names}) == len(names),
                "release ZIP has case-colliding paths")
        total = 0
        for entry in entries:
            name = entry.filename
            require(name == Path(name).as_posix() and not name.startswith("/")
                    and "\\" not in name and ":" not in name
                    and all(part not in ("", ".", "..") for part in name.split("/")),
                    f"unsafe ZIP path: {name!r}")
            kind = stat.S_IFMT(entry.external_attr >> 16)
            require(kind in (0, stat.S_IFREG) and not entry.is_dir(),
                    f"nonregular ZIP member: {name}")
            require(not entry.flag_bits & 1, f"encrypted ZIP member: {name}")
            require(entry.compress_type in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED),
                    f"unsupported ZIP compression: {name}")
            require(entry.file_size <= EXPANDED_LIMIT, f"oversized ZIP member: {name}")
            total += entry.file_size
            require(total <= EXPANDED_LIMIT, "ZIP expansion limit exceeded")
    print("Whole ZIP digest, exact 82-file roster and expansion bounds PASS")


def extract_verified_zip(zip_path, root):
    # root is an empty directory created exclusively by TemporaryDirectory.
    require(not any(root.iterdir()), "extraction directory is not empty")
    with zipfile.ZipFile(zip_path) as archive:
        for entry in archive.infolist():
            target = root / entry.filename
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(entry) as source, target.open("xb") as output:
                shutil.copyfileobj(source, output, 1024 * 1024)
            require(target.stat().st_size == entry.file_size,
                    f"short ZIP member: {entry.filename}")
    if sys.platform == "linux":
        for command in ("uacd", "uacd-gui"):
            (root / "linux-x86_64" / command).chmod(0o755)
    verify_bundle(root)


def expected_dirs(files):
    return {"/".join(name.split("/")[:i]) for name in files
            for i in range(1, len(name.split("/")))}


def verify_bundle(root, installed=False):
    require(root.is_dir() and not root.is_symlink(), "bundle is not an ordinary directory")
    files, dirs = set(), set()
    for base, subdirs, filenames in os.walk(root, followlinks=False):
        for name in subdirs + filenames:
            item = Path(base) / name
            relative = item.relative_to(root).as_posix()
            mode = item.lstat().st_mode
            if stat.S_ISDIR(mode):
                dirs.add(relative)
            elif stat.S_ISREG(mode):
                files.add(relative)
            else:
                raise ValueError(f"nonregular package entry: {relative}")
    expected_files = PACKAGE_FILES | ({"INSTALL_RECEIPT"} if installed else set())
    require(files == expected_files and dirs == expected_dirs(PACKAGE_FILES),
            "package file or directory roster mismatch")
    manifest = (root / "SHA256SUMS").read_bytes()
    expected_manifest = "".join(
        f"{sha256(root / name)}  {name}\n" for name in sorted(PAYLOAD)
    ).encode("ascii")
    require(manifest == expected_manifest, "package SHA256SUMS or payload checksum mismatch")
    if installed:
        receipt = (f"Gradient Data {VERSION}\n" + hashlib.sha256(manifest).hexdigest()
                   + "\n").encode("ascii")
        require((root / "INSTALL_RECEIPT").read_bytes() == receipt,
                "installed bundle receipt mismatch")
    print("Installed" if installed else "Extracted", "public manifest and exact roster PASS")


def run(*command, env=None):
    result = subprocess.run([str(item) for item in command], env=env,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                            encoding="utf-8", errors="strict", timeout=180)
    if result.returncode:
        raise RuntimeError(f"command failed ({result.returncode}): {command!r}\n"
                           f"stdout: {result.stdout[-3000:]}\nstderr: {result.stderr[-3000:]}")
    return result


def clean_runtime_environment(bundle, environment):
    env = environment.copy()
    env.pop("LD_LIBRARY_PATH", None)
    if sys.platform == "win32":
        def in_bundle(text):
            try:
                path = Path(text).resolve()
                return path == bundle or bundle in path.parents
            except (OSError, ValueError):
                return False
        env["PATH"] = os.pathsep.join(part for part in env.get("PATH", "").split(os.pathsep)
                                      if part and not in_bundle(part))
    return env


def generated_input():
    # Deterministic non-power-of-two skew, with no private corpus or fixture.
    state = 0x48723995afcb02d1
    thresholds = (52, 92, 123, 150, 173, 192, 207, 219, 229, 237,
                  243, 247, 250, 252, 254, 255)
    raw = bytearray()
    for _ in range(300_003):
        state ^= (state << 13) & ((1 << 64) - 1)
        state ^= state >> 7
        state ^= (state << 17) & ((1 << 64) - 1)
        value = (state >> 24) & 255
        raw.append(next(i for i, limit in enumerate(thresholds) if value <= limit))
    return bytes(raw)


def exercise_folder_inputs(cli, work, runtime):
    """Small public examples: generated bytes, names and empty directory entries."""
    source = work / "example folder"
    source.mkdir()
    (source / "empty directory").mkdir()
    (source / "notes").mkdir()
    member_source = source / "café.dat"
    member_bytes = bytes(range(256)) * 24 + b"Public example bytes with CRLF.\r\n"
    relative_files = {"café.dat": member_bytes, "empty.dat": b"",
                      "notes/readme.txt": b"Generated public consumer example.\n"}
    for name, content in relative_files.items():
        (source / name).write_bytes(content)
    extra = work / "selected.txt"
    extra.write_bytes(b"A separately selected file.\n")
    source_hashes = {name: sha256(source / name) for name in relative_files}
    extra_hash = sha256(extra)
    member = source.name + "/café.dat"
    directories = {source.name, source.name + "/empty directory", source.name + "/notes"}
    folder = work / "folder.uacd"
    multiple = work / "multiple.uacd"
    run(cli, "pack", source, folder, "--profile", "fast", "--block-size", "64KiB", env=runtime)
    run(cli, "pack-many", multiple, source, extra, "--profile", "fast",
        "--block-size", "64KiB", env=runtime)

    def rejected(*arguments):
        result = subprocess.run([str(cli), *map(str, arguments)], env=runtime,
                                capture_output=True, timeout=180)
        require(result.returncode != 0, "folder operation unexpectedly accepted a protected destination or limit")

    for archive, additional in ((folder, {}), (multiple, {extra.name: extra.read_bytes()})):
        with archive.open("rb") as stream:
            require(stream.read(8) == b"UACD0004", "folder archive version mismatch")
        files = {source.name + "/" + name: content for name, content in relative_files.items()}
        files.update(additional)
        listing = json.loads(run(cli, "list", archive, env=runtime).stdout)
        require({entry["path"] for entry in listing["entries"]} == set(files) | directories,
                "folder or selected-root names mismatch")
        info = json.loads(run(cli, "info", archive, env=runtime).stdout)
        require(info["version"] == 4 and info["raw_bytes"] == sum(map(len, files.values()))
                and info["archive_bytes"] == archive.stat().st_size,
                "folder dimensions mismatch")
        run(cli, "verify", archive, env=runtime)
        destination = work / (archive.stem + "-restored")
        run(cli, "unpack", archive, destination, env=runtime)
        for name, content in files.items():
            require((destination / name).read_bytes() == content, "folder whole-file byte mismatch")
        for name in directories:
            require((destination / name).is_dir(), "folder directory entry missing")
        rejected("unpack", archive, destination)
        for name, content in files.items():
            require((destination / name).read_bytes() == content, "existing output tree was changed")
        existing_empty = work / (archive.stem + "-existing-empty")
        existing_empty.mkdir()
        rejected("unpack", archive, existing_empty)
        require(not any(existing_empty.iterdir()), "existing empty output directory was changed")
        selected = work / (archive.stem + "-member.dat")
        run(cli, "extract", archive, member, selected, env=runtime)
        require(selected.read_bytes() == member_bytes, "selected member byte mismatch")
        rejected("extract", archive, member, selected)
        require(selected.read_bytes() == member_bytes, "existing selected member was changed")
        segment = work / (archive.stem + "-range.dat")
        run(cli, "range", archive, "11", "257", segment, "--file", member, env=runtime)
        require(segment.read_bytes() == member_bytes[11:268], "selected member range byte mismatch")
        blocked = work / (archive.stem + "-limited")
        rejected("unpack", archive, blocked, "--max-output", info["raw_bytes"] - 1)
        require(not blocked.exists(), "admission refusal published an output")
        rejected("list", archive, "--max-index", info["index_bytes"] - 1)
        rejected("list", archive, "--max-entries", info["entries"] - 1)
        before = sha256(archive)
        rejected("pack", source, archive, "--profile", "fast")
        require(sha256(archive) == before, "folder pack replaced an existing archive")
    require(source_hashes == {name: sha256(source / name) for name in relative_files}
            and sha256(extra) == extra_hash, "generated source files changed")
    require(not any(item.name.startswith(".uacd.partial-") for item in work.iterdir()),
            "folder operation left partial staging")
    print("Folder and multiple-root CLI roundtrip/member/range/no-overwrite/admission PASS")
    return multiple, member, member_source


def exercise_workers(cli, source, data, work, runtime):
    """Actual installed process quota and two-block ordered byte parity."""
    archives = []
    for workers in (1, 2):
        archive = work / f"worker-{workers}.uacd"
        result = run(cli, "pack", source, archive, "--profile", "fast",
                     "--block-size", "64KiB", "--workers", workers,
                     "--memory-budget", "1GiB", env=runtime)
        policy = "windows-committed" if sys.platform == "win32" else "linux-address-space"
        require("memory_policy=" + policy in result.stderr,
                "installed CLI did not report its actual quota policy")
        restored = work / f"worker-{workers}.restored"
        run(cli, "unpack", archive, restored, env=runtime)
        require(restored.read_bytes() == data, "installed worker reconstruction mismatch")
        archives.append(archive)
    require(sha256(archives[0]) == sha256(archives[1]), "installed workers changed archive bytes")
    for index, flags in enumerate((("--workers", "3"), ("--workers", "2", "--memory-budget", "1"))):
        rejected = work / f"worker-rejected-{index}.uacd"
        before = set(work.iterdir())
        result = subprocess.run([str(cli), "pack", str(source), str(rejected), *flags],
                                env=runtime, capture_output=True, timeout=180)
        require(result.returncode != 0 and not rejected.exists() and set(work.iterdir()) == before,
                "invalid workers/quota created output or staging")
    require(source.read_bytes() == data, "worker smoke modified source")
    print("Installed 1/2 worker exact bytes, OS quota reporting and early refusal PASS")


def exercise_runtime_reader(executable, archive, member, source, runtime):
    """C11/shared or C++17/static; identical returned windows, unmanaged cache."""
    raw = source.read_bytes()
    n = min(len(raw), 4096)
    expected = [(0, n), ((len(raw) - n) // 2, n), (len(raw) - n, n)]
    for mode, args in (("archive", [archive, member]), ("loose", [source])):
        result = run(executable, mode, *args, env=runtime)
        value = json.loads(result.stdout)
        require(value.get("schema") == "uacd-runtime-reader-v1" and value.get("status") == 0
                and value.get("logical_bytes") == len(raw), "runtime reader dimensions/status")
        require(value.get("cache_state") == "unmanaged" and value.get("full_verify_called") is False
                and value.get("unpack_called") is False, "runtime reader changed service")
        require(len(value.get("windows", [])) == len(expected), "runtime reader missing windows")
        for window, (offset, length) in zip(value["windows"], expected):
            require(window.get("status") == 0 and window.get("offset") == offset
                    and window.get("requested_bytes") == length and window.get("returned_bytes") == length
                    and window.get("sha256") == hashlib.sha256(raw[offset:offset + length]).hexdigest(),
                    "runtime reader returned different bytes")
    print("Installed bounded runtime reader archive/loose window hashes PASS")


def exercise_gui(gui, runtime):
    """Minimal native companion serve/auth gate; session details stay in memory."""
    try:
        version = subprocess.run([str(gui), "--version"], env=runtime, capture_output=True,
                                 timeout=180)
    except OSError:
        raise RuntimeError("GUI companion version check could not start") from None
    except subprocess.TimeoutExpired:
        raise RuntimeError("GUI companion version check did not finish") from None
    require(version.returncode == 0 and version.stdout.strip() == f"gradient-data {VERSION}".encode(),
            "GUI companion version differs from release")
    try:
        process = subprocess.Popen([str(gui), "--no-browser"], env=runtime,
                                   stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    except OSError:
        raise RuntimeError("GUI companion could not start") from None
    startup = queue.Queue(maxsize=1)
    def read_startup():
        try:
            line = process.stdout.readline(512)
        except (OSError, UnicodeError, ValueError):
            line = ""
        startup.put(line)
    reader = threading.Thread(target=read_startup, daemon=True)
    reader.start()
    try:
        try:
            line = startup.get(timeout=30).strip()
        except queue.Empty:
            raise RuntimeError("GUI startup response missing") from None
        require(line.startswith("UACD_GUI_URL="), "GUI startup response missing")
        try:
            endpoint = urlsplit(line.split("=", 1)[1])
            port = endpoint.port
        except ValueError:
            raise RuntimeError("GUI startup endpoint invalid") from None
        require(endpoint.scheme == "http" and endpoint.hostname == "127.0.0.1"
                and port is not None and 0 < port < 65536
                and endpoint.netloc == f"127.0.0.1:{port}" and endpoint.path == "/"
                and not endpoint.query and re.fullmatch(r"[0-9a-f]{64}", endpoint.fragment),
                "GUI startup endpoint invalid")
        origin = "http://" + endpoint.netloc

        def request(method, route, expected, headers=None):
            connection = http.client.HTTPConnection("127.0.0.1", port, timeout=15)
            try:
                body = b"{}" if method == "POST" else None
                connection.request(method, route, body=body, headers=headers or {})
                response = connection.getresponse()
                content = response.read(65537)
                require(len(content) <= 65536, "GUI response exceeds consumer bound")
                require(response.status == expected, "GUI serve or authentication status mismatch")
                require(response.getheader("Access-Control-Allow-Origin") is None,
                        "GUI unexpectedly enabled cross-origin access")
                return content
            except (OSError, http.client.HTTPException):
                raise RuntimeError("GUI HTTP request failed") from None
            finally:
                connection.close()

        require(bool(request("GET", "/", 200)), "GUI did not serve its local page")
        unauthenticated = {"Origin": origin, "Content-Type": "application/json"}
        request("POST", "/api/status", 403, unauthenticated)
        authorized = {**unauthenticated, "X-Uacd-Token": endpoint.fragment}
        wrong_origin = {**authorized, "Origin": "https://example.invalid"}
        request("POST", "/api/status", 403, wrong_origin)
        status = json.loads(request("POST", "/api/status", 200, authorized))
        require(status.get("state") == "idle", "GUI authenticated status mismatch")
        request("POST", "/api/shutdown", 200, authorized)
        try:
            require(process.wait(timeout=15) == 0, "GUI shutdown failed")
        except subprocess.TimeoutExpired:
            raise RuntimeError("GUI shutdown did not finish") from None
        print("Native GUI version, local HTTP page, authentication and shutdown PASS")
    finally:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                process.kill()
                try:
                    process.wait(timeout=15)
                except subprocess.TimeoutExpired:
                    raise RuntimeError("GUI process cleanup did not finish") from None
        reader.join(timeout=1)
        process.stdout.close()
        process.stderr.close()


def compare_member_output(executable, archive, member, source, runtime):
    with source.open("rb") as stream:
        expected = stream.read(4096)
    result = subprocess.run([str(executable), str(archive), member], env=runtime,
                            capture_output=True, timeout=180)
    require(result.returncode == 0, "archive member SDK consumer failed")
    require(result.stdout == expected, "archive member SDK stdout bytes mismatch")


def exercise_installed(bundle, work, environment):
    windows = sys.platform == "win32"
    platform_dir = bundle / ("windows-x86_64" if windows else "linux-x86_64")
    cli = platform_dir / ("uacd.exe" if windows else "uacd")
    gui = platform_dir / ("uacd-gui.exe" if windows else "uacd-gui")
    runtime = clean_runtime_environment(bundle, environment)
    data = generated_input()
    source = work / "synthetic.bin"
    source.write_bytes(data)
    require(run(cli, "--version", env=runtime).stdout.strip() == f"gradient-data {VERSION}",
            "installed CLI version differs from release")
    for mode in ("off", "local", "shared"):
        archive = work / f"{mode}.uacd"
        restored = work / f"{mode}.restored"
        segment = work / f"{mode}.range"
        run(cli, "pack", source, archive, "--profile", "fast", "--entropy", mode, env=runtime)
        magic = archive.read_bytes()[:8]
        require(magic == (b"DGRAD001" if mode == "off" else b"UACD0003"),
                f"unexpected {mode} archive version: {magic!r}")
        run(cli, "info", archive, env=runtime)
        run(cli, "verify", archive, env=runtime)
        run(cli, "range", archive, "260000", "8192", segment, env=runtime)
        require(segment.read_bytes() == data[260000:268192], f"{mode} range mismatch")
        run(cli, "unpack", archive, restored, env=runtime)
        require(restored.read_bytes() == data, f"{mode} unpack mismatch")
        blocked = subprocess.run([str(cli), "unpack", str(archive), str(restored)],
                                 env=runtime, capture_output=True)
        require(blocked.returncode != 0 and restored.read_bytes() == data,
                f"{mode} overwrite protection failed")
        print(f"{mode} CLI verify/range/unpack/no-overwrite PASS")

    exercise_workers(cli, source, data, work, runtime)
    member_archive, member_name, member_source = exercise_folder_inputs(cli, work, runtime)
    exercise_gui(gui, runtime)
    build = work / "build"
    run("cmake", "-S", bundle / "examples", "-B", build,
        "-DGradientData_DIR=" + str(bundle / "cmake"), env=environment)
    run("cmake", "--build", build, "--config", "Release", env=environment)
    exe_dir = build / "Release" if windows and (build / "Release").is_dir() else build
    suffix = ".exe" if windows else ""
    if windows:
        dll = platform_dir / "gradient_data_c.dll"
        deployed = exe_dir / dll.name
        shutil.copyfile(dll, deployed)
        require(sha256(deployed) == sha256(dll), "deployed C SDK DLL differs from bundle")
    for name in ("read_range_c", "read_range_cpp"):
        executable = exe_dir / (name + suffix)
        for mode in ("off", "local", "shared"):
            run(executable, work / f"{mode}.uacd", env=runtime)
    print("C11 shared and C++17 static CMake consumers on all archives PASS")
    for name in ("read_member_c", "read_member_cpp"):
        compare_member_output(exe_dir / (name + suffix), member_archive,
                              member_name, member_source, runtime)
    print("C11 shared and C++17 static archive member consumers: exact stdout bytes PASS")
    for name in ("runtime_asset_reader_c", "runtime_asset_reader_cpp"):
        exercise_runtime_reader(exe_dir / (name + suffix), member_archive,
                                member_name, member_source, runtime)



def install_and_exercise(bundle, scratch):
    environment = os.environ.copy()
    if sys.platform == "win32":
        environment["LOCALAPPDATA"] = str(scratch / "local-app-data")
        prefix = scratch / "local-app-data/Programs/GradientData" / VERSION
        install = ["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy",
                   "Bypass", "-File", str(bundle / "install.ps1")]
        uninstall = ["powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy",
                     "Bypass", "-File", str(bundle / "uninstall.ps1")]
    elif sys.platform == "linux":
        environment["XDG_DATA_HOME"] = str(scratch / "xdg-data")
        environment["XDG_BIN_HOME"] = str(scratch / "xdg-bin")
        prefix = scratch / "xdg-data/gradient-data" / VERSION
        install = ["sh", str(bundle / "install.sh")]
        uninstall = ["sh", str(bundle / "uninstall.sh")]
    else:
        raise RuntimeError("only Linux and Windows x86-64 runners are supported")
    require(not prefix.exists() and not prefix.is_symlink(), "test installation exists")
    run(*install, env=environment)
    require(prefix.is_dir() and not prefix.is_symlink(), "installer did not create prefix")
    verify_bundle(prefix, installed=True)
    usage = scratch / "usage"
    usage.mkdir()
    exercise_installed(prefix, usage, environment)
    run(*uninstall, env=environment)
    require(not prefix.exists() and not prefix.is_symlink(), "uninstaller left prefix")
    if sys.platform == "linux":
        for command in ("uacd", "uacd-gui"):
            link = scratch / "xdg-bin" / command
            require(not link.exists() and not link.is_symlink(), "uninstaller left its own command link")
    print("isolated user-local install and uninstall PASS")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-tag", required=True,
                        help="tag of the published Gradient19/gradient-data release")
    arguments = parser.parse_args()
    tag = arguments.release_tag
    require(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", tag) is not None,
            "invalid public release tag")
    with tempfile.TemporaryDirectory(prefix="gradient-data-public-smoke-") as temporary:
        scratch = Path(temporary)
        zip_path = scratch / ASSET
        sidecar = scratch / (ASSET + ".sha256")
        download(tag, sidecar.name, sidecar, 256)
        download(tag, ASSET, zip_path, ZIP_LIMIT)
        check_sidecar(sidecar, zip_path)
        check_zip(zip_path)
        bundle = scratch / "bundle"
        bundle.mkdir()
        extract_verified_zip(zip_path, bundle)
        install_and_exercise(bundle, scratch)
    print("Public release customer smoke PASS")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, RuntimeError, zipfile.BadZipFile, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"customer smoke failed: {error}") from error
